### PR TITLE
rwcarlsen -> cyclus for cycamore repo

### PR DESCRIPTION
**Pull request by gidden**
this fixes the issue jee hoon saw

### CODE REVIEW

**Comment by rwcarlsen** [comment]
I'd prefer we fix this in cyclus/cloudlus only.  Because for my research,
it is not unlikely I will want it to be rwcarlsen/cyclus.

**Comment by gidden** [comment]
We need a cyclus/cloudlus first =)

On Wed, Jul 15, 2015 at 1:09 PM, Robert Carlsen notifications@github.com
wrote:

> I'd prefer we fix this in cyclus/cloudlus only. Because for my research,
> it is not unlikely I will want it to be rwcarlsen/cyclus.
> 
> On Mon, Jul 6, 2015 at 4:42 PM, Matthew Gidden notifications@github.com
> wrote:
> 
> > ## this fixes the issue jee hoon saw
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/rwcarlsen/cloudlus/pull/2
> > Commit Summary
> > - rwcarlsen -> cyclus for cycamore repo
> > 
> > File Changes
> > - _M_ Dockerfile
> >   https://github.com/rwcarlsen/cloudlus/pull/2/files#diff-0 (2)
> > 
> > Patch Links:
> > - https://github.com/rwcarlsen/cloudlus/pull/2.patch
> > - https://github.com/rwcarlsen/cloudlus/pull/2.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/rwcarlsen/cloudlus/pull/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rwcarlsen/cloudlus/pull/2#issuecomment-121697607.

## 

Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
done.

**Comment by gidden** [comment]
ok, I'll merge these in to cyclus/cloudlus

**Pull request closed without merging**
